# -*- coding: utf-8 -*-
"""request

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_jp7WeRkUAIbVNPIZOqbQS-m_tsNb2nN
"""

import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'year':2024})

print(r.json())